In [2]:
import pandas as pd
import requests 
import simplejson as json
import quandl

In [19]:
r = requests.get('https://www.quandl.com/api/v3/datatables/WIKI/PRICES.json?api_key=XyT1FY3chW_8gD_g4ytW')

In [21]:
r.headers

{'Date': 'Sat, 30 Dec 2017 03:37:44 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d957ccf9db9398b8770e0bf7f920fc1071514605063; expires=Sun, 30-Dec-18 03:37:43 GMT; path=/; domain=.quandl.com; HttpOnly', 'Cache-Control': 'max-age=0, private, must-revalidate', 'Cursor_ID': 'djFfMTAwMDFfMTUxNDYwNTA2NA==', 'ETag': 'W/"3818d1fa9a59e7abfe9934056c3b4f21"', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-RateLimit-Limit': '50000', 'X-RateLimit-Remaining': '49991', 'X-Request-Id': 'bf4c9ecd-6bd1-48f5-8ab2-3e20fb7b37c0', 'X-Runtime': '0.643433', 'X-XSS-Protection': '1; mode=block', 'Server': 'cloudflare-nginx', 'CF-RAY': '3d51f64f1faf23f0-IAD', 'Content-Encoding': 'gzip'}

In [15]:
df=pd.read_json('https://www.quandl.com/api/v3/datatables/WIKI/PRICES.json?api_key=XyT1FY3chW_8gD_g4ytW')

In [17]:
df['datatable']

columns           [{'name': 'ticker', 'type': 'String'}, {'name'...
data              [[A, 1999-11-18, 45.5, 50.0, 40.0, 44.0, 44739...
next_cursor_id                                                  NaN
Name: datatable, dtype: object

In [35]:
dictionary = {'api_key':'XyT1FY3chW_8gD_g4ytW', 'date.lt':'2017-11-30', 'date.gt':'2017-11-01'}
r = requests.get('https://www.quandl.com/api/v3/datatables/WIKI/PRICES.json', params=dictionary)
x = r.json()
x.keys()

dict_keys(['datatable', 'meta'])

In [3]:
r=quandl.get("https://www.quandl.com/api/v3/datatables/WIKI/PRICES.json?api_key=XyT1FY3chW_8gD_g4ytW", start_date="2017-12-01")

ValueError: The column index must be expressed as an integer for https://www.quandl.com/api/v3/datatables/WIKI/PRICES.json?api_key=XyT1FY3chW_8gD_g4ytW.

In [5]:
data = quandl.get("WIKI/PRICES", start_date="2017-11-01", end_date="2017-11-30")

NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.

In [27]:
x.keys()

dict_keys(['quandl_error'])

In [18]:
df=pd.DataFrame(x['datatable']['columns'])

           name               type
0        ticker             String
1          date               Date
2          open  BigDecimal(34,12)
3          high  BigDecimal(34,12)
4           low  BigDecimal(34,12)
5         close  BigDecimal(34,12)
6        volume  BigDecimal(37,15)
7   ex-dividend  BigDecimal(42,20)
8   split_ratio             double
9      adj_open  BigDecimal(50,28)
10     adj_high  BigDecimal(50,28)
11      adj_low  BigDecimal(50,28)
12    adj_close  BigDecimal(50,28)
13   adj_volume             double

In [36]:
pd.DataFrame(x['datatable']['data'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,A,2017-11-02,68.08,68.3800,67.810,68.13,1854678.0,0.0,1.0,68.08,68.3800,67.810,68.13,1854678.0
1,A,2017-11-03,68.09,68.6700,68.010,68.37,1070662.0,0.0,1.0,68.09,68.6700,68.010,68.37,1070662.0
2,A,2017-11-06,68.27,68.4500,67.870,68.22,991668.0,0.0,1.0,68.27,68.4500,67.870,68.22,991668.0
3,A,2017-11-07,68.32,68.6400,68.040,68.25,946235.0,0.0,1.0,68.32,68.6400,68.040,68.25,946235.0
4,A,2017-11-09,67.92,67.9800,66.910,67.47,1664971.0,0.0,1.0,67.92,67.9800,66.910,67.47,1664971.0
5,A,2017-11-10,67.35,67.5800,66.700,66.81,1704341.0,0.0,1.0,67.35,67.5800,66.700,66.81,1704341.0
6,A,2017-11-13,66.45,67.3900,66.250,67.13,1443239.0,0.0,1.0,66.45,67.3900,66.250,67.13,1443239.0
7,A,2017-11-14,66.98,67.8000,66.890,67.46,1682158.0,0.0,1.0,66.98,67.8000,66.890,67.46,1682158.0
8,A,2017-11-15,67.29,67.5600,66.910,67.31,1511323.0,0.0,1.0,67.29,67.5600,66.910,67.31,1511323.0
9,A,2017-11-16,67.50,68.9500,67.450,68.74,2268333.0,0.0,1.0,67.50,68.9500,67.450,68.74,2268333.0
10,A,2017-11-17,68.53,69.0900,68.290,68.79,1816997.0,0.0,1.0,68.53,69.0900,68.290,68.79,1816997.0
11,A,2017-11-20,69.28,70.2300,68.950,69.96,4014526.0,0.0,1.0,69.28,70.2300,68.950,69.96,4014526.0
12,A,2017-11-21,70.05,70.8100,67.700,69.91,5329997.0,0.0,1.0,70.05,70.8100,67.700,69.91,5329997.0
13,A,2017-11-22,69.14,69.3700,68.300,68.69,3041633.0,0.0,1.0,69.14,69.3700,68.300,68.69,3041633.0
14,A,2017-11-24,68.84,69.3900,68.780,69.36,1015411.0,0.0,1.0,68.84,69.3900,68.780,69.36,1015411.0
15,A,2017-11-27,69.22,69.4900,69.170,69.31,1439274.0,0.0,1.0,69.22,69.4900,69.170,69.31,1439274.0
16,A,2017-11-28,69.56,70.9300,69.420,70.59,2275971.0,0.0,1.0,69.56,70.9300,69.420,70.59,2275971.0
17,A,2017-11-29,70.50,70.8400,68.450,68.69,1903991.0,0.0,1.0,70.50,70.8400,68.450,68.69,1903991.0
18,AA,2017-11-02,47.68,47.7671,47.070,47.46,2057632.0,0.0,1.0,47.68,47.7671,47.070,47.46,2057632.0
19,AA,2017-11-03,47.25,47.4300,46.710,47.12,1837775.0,0.0,1.0,47.25,47.4300,46.710,47.12,1837775.0
20,AA,2017-11-06,47.20,47.6800,46.530,47.29,1725268.0,0.0,1.0,47.20,47.6800,46.530,47.29,1725268.0
21,AA,2017-11-07,47.11,47.2042,46.540,46.97,2163621.0,0.0,1.0,47.11,47.2042,46.540,46.97,2163621.0
22,AA,2017-11-09,44.71,44.7100,43.110,43.33,7661245.0,0.0,1.0,44.71,44.7100,43.110,43.33,7661245.0
23,AA,2017-11-10,42.93,44.4600,42.750,43.01,4441527.0,0.0,1.0,42.93,44.4600,42.750,43.01,4441527.0
24,AA,2017-11-13,42.70,43.8700,42.550,43.13,3162683.0,0.0,1.0,42.70,43.8700,42.550,43.13,3162683.0
25,AA,2017-11-14,42.90,42.9000,40.620,41.87,8095739.0,0.0,1.0,42.90,42.9000,40.620,41.87,8095739.0
26,AA,2017-11-15,41.27,42.3700,40.730,42.21,4726434.0,0.0,1.0,41.27,42.3700,40.730,42.21,4726434.0
27,AA,2017-11-16,42.68,43.0800,42.060,42.30,3328098.0,0.0,1.0,42.68,43.0800,42.060,42.30,3328098.0
28,AA,2017-11-17,42.00,43.6000,42.000,43.40,3569042.0,0.0,1.0,42.00,43.6000,42.000,43.40,3569042.0
29,AA,2017-11-20,42.29,42.5500,41.750,42.21,4844213.0,0.0,1.0,42.29,42.5500,41.750,42.21,4844213.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,CSGP,2017-11-14,295.41,299.9600,294.730,299.05,196169.0,0.0,1.0,295.41,299.9600,294.730,299.05,196169.0
9971,CSGP,2017-11-15,297.20,298.5400,293.990,297.31,106573.0,0.0,1.0,297.20,298.5400,293.990,297.31,106573.0
9972,CSGP,2017-11-16,298.67,304.6300,297.390,303.53,220675.0,0.0,1.0,298.67,304.6300,297.390,303.53,220675.0
9973,CSGP,2017-11-17,304.53,306.6900,303.670,304.74,223972.0,0.0,1.0,304.53,306.6900,303.670,304.74,223972.0
9974,CSGP,2017-11-20,305.69,307.5200,303.010,306.63,175065.0,0.0,1.0,305.69,307.5200,303.010,306.63,175065.0
9975,CSGP,2017-11-21,307.77,311.0800,307.150,307.97,171773.0,0.0,1.0,307.77,311.0800,307.150,307.97,171773.0
9976,CSGP,2017-11-22,308.52,309.5600,304.710,308.80,163779.0,0.0,1.0,308.52,309.5600,304.710,308.80,163779.0
9977,CSGP,2017-11-24,309.44,314.7299,308.980,310.19,65907.0,0.0,1.0,309.44,314.7299,308.980,310.19,65907.0
9978,CSGP,2017-11-27,310.18,313.7500,309.005,309.49,170787.0,0.0,1.0,310.18,313.7500,309.005,309.49,170787.0
9979,CSGP,2017-11-28,309.23,310.6400,306.230,307.42,200383.0,0.0,1.0,309.23,310.6400,306.230,307.42,200383.0
9980,CSGP,2017-11-29,308.18,308.5050,298.570,301.86,200249.0,0.0,1.0,308.18,308.5050,298.570,301.86,200249.0
9981,CSGS,2017-11-02,43.20,45.1900,42.290,44.88,244389.0,0.0,1.0,43.20,45.1900,42.290,44.88,244389.0
9982,CSGS,2017-11-03,42.86,44.4250,42.505,43.68,236914.0,0.0,1.0,42.86,44.4250,42.505,43.68,236914.0
9983,CSGS,2017-11-06,43.41,44.3300,43.250,44.12,78291.0,0.0,1.0,43.41,44.3300,43.250,44.12,78291.0
9984,CSGS,2017-11-07,44.10,44.2600,43.180,43.45,83272.0,0.0,1.0,44.10,44.2600,43.180,43.45,83272.0
9985,CSGS,2017-11-09,43.42,43.8200,43.250,43.63,63937.0,0.0,1.0,43.42,43.8200,43.250,43.63,63937.0
9986,CSGS,2017-11-10,43.44,43.9350,43.440,43.50,85383.0,0.0,1.0,43.44,43.9350,43.440,43.50,85383.0
9987,CSGS,2017-11-13,43.32,43.8500,43.230,43.58,124891.0,0.0,1.0,43.32,43.8500,43.230,43.58,124891.0
9988,CSGS,2017-11-14,43.33,43.6300,42.840,42.95,86628.0,0.0,1.0,43.33,43.6300,42.840,42.95,86628.0
9989,CSGS,2017-11-15,42.66,43.0700,42.440,42.86,101800.0,0.0,1.0,42.66,43.0700,42.440,42.86,101800.0
9990,CSGS,2017-11-16,42.99,44.2600,42.990,44.05,95165.0,0.0,1.0,42.99,44.2600,42.990,44.05,95165.0
9991,CSGS,2017-11-17,43.78,44.1000,42.800,43.72,122159.0,0.0,1.0,43.78,44.1000,42.800,43.72,122159.0
9992,CSGS,2017-11-20,43.79,44.3400,43.210,44.23,84342.0,0.0,1.0,43.79,44.3400,43.210,44.23,84342.0
9993,CSGS,2017-11-21,44.16,45.0000,43.930,44.96,108948.0,0.0,1.0,44.16,45.0000,43.930,44.96,108948.0
9994,CSGS,2017-11-22,44.72,45.0600,44.650,44.88,83680.0,0.0,1.0,44.72,45.0600,44.650,44.88,83680.0
9995,CSGS,2017-11-24,45.01,45.0100,43.610,44.63,71705.0,0.0,1.0,45.01,45.0100,43.610,44.63,71705.0
9996,CSGS,2017-11-27,44.78,45.3500,44.780,45.06,186341.0,0.0,1.0,44.78,45.3500,44.780,45.06,186341.0
9997,CSGS,2017-11-28,45.13,46.0400,44.960,45.96,98917.0,0.0,1.0,45.13,46.0400,44.960,45.96,98917.0
9998,CSGS,2017-11-29,45.91,46.3500,45.670,45.98,112082.0,0.0,1.0,45.91,46.3500,45.670,45.98,112082.0
9999,CSII,2017-11-02,24.57,25.4700,24.190,24.27,300440.0,0.0,1.0,24.57,25.4700,24.190,24.27,300440.0

In [9]:
x['datatable'].keys()

dict_keys(['data', 'columns'])

In [7]:
df = pd.DataFrame(x['datatable'])

KeyError: 'data'

In [5]:
df

,datatable,meta
columns,"[{'name': 'ticker', 'type': 'String'}, {'name'...",NaN
data,"[[A, 1999-11-18, 45.5, 50.0, 40.0, 44.0, 44739...",NaN
next_cursor_id,NaN,djFfMTAwMDFfMTUxNDYwNTc3NA==